//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevSumScheduler.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevSumScheduler.Tests.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;ie ie7 ltie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;ie ie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if !(IE 7) | !(IE 8)  ]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;ie ie7 ltie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;ie ie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if !(IE 7) | !(IE 8)  ]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;ie ie7 ltie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;ie ie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if !(IE 7) | !(IE 8)  ]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Speaker1 {
            get {
                return ResourceManager.GetString("Speaker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;!--[if IE 7]&gt;&lt;html class=&quot;ie ie7 ltie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;&lt;html class=&quot;ie ie8 ltie9&quot; lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;&lt;![endif]--&gt;
        ///&lt;!--[if !(IE 7) | !(IE 8)  ]&gt;&lt;!--&gt;
        ///&lt;html lang=&quot;sv-SE&quot; prefix=&quot;og: http://ogp.me/ns#&quot; xmlns:og=&quot;http://ogp.me/ns#&quot; xmlns:fb=&quot;http://ogp.me/ns/fb#&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Speaker2 {
            get {
                return ResourceManager.GetString("Speaker2", resourceCulture);
            }
        }
    }
}
